version: '3.8'

services:
  backend-monolith:
    container_name: RA_BACKEND_MONOLITH
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - shared_backend_data:/data
    restart: unless-stopped

volumes:
  shared_backend_data:
