import { useState, useEffect } from 'react';
import axios from 'axios';
import { ArrowLeft, Brain, Cpu, Calendar, Award, Lightbulb } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

const getErrorMessage = (err, fallback) => {
  const detail = err.response?.data?.detail;
  if (!detail) return fallback;
  if (typeof detail === 'string') return detail;
  if (Array.isArray(detail)) {
    return detail.map(d => {
      const field = d.loc && d.loc.length > 1 ? d.loc[d.loc.length - 1] : '';
      return field ? `${field}: ${d.msg}` : d.msg;
    }).join(', ');
  }
  if (typeof detail === 'object') {
    return JSON.stringify(detail);
  }
  return fallback;
};

export default function AnalysisDetails({ token, resumeId, onBack }) {
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchAnalysis = async () => {
      try {
        const resp = await axios.get(`${API_URL}/resume/analysis/${resumeId}`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        setAnalysis(resp.data);
      } catch (err) {
        console.error('Failed to fetch analysis:', err);
        setError(
          getErrorMessage(err, 'Failed to load analysis details. It might still be processing.')
        );
      } finally {
        setLoading(false);
      }
    };

    fetchAnalysis();
  }, [resumeId]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] gap-3">
        <span className="w-8 h-8 border-3 border-indigo-500/20 border-t-indigo-600 rounded-full animate-spin" />
        <p className="text-xs text-slate-500">Loading analysis results...</p>
      </div>
    );
  }

  if (error || !analysis) {
    return (
      <div className="max-w-xl mx-auto px-4 py-10 text-center space-y-4">
        <div className="w-12 h-12 bg-red-50 border border-red-200 rounded-full flex items-center justify-center mx-auto text-red-600">
          <Brain className="w-6 h-6" />
        </div>
        <h3 className="text-lg font-bold text-slate-800">Failed to Load Analysis</h3>
        <p className="text-xs text-slate-500">{error}</p>
        <button
          onClick={onBack}
          className="border border-slate-300 hover:bg-slate-50 text-slate-700 font-medium px-4 py-2 rounded-lg inline-flex items-center gap-1.5 text-xs active:scale-95 transition-all"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Dashboard</span>
        </button>
      </div>
    );
  }

  const score = analysis.match_score;
  const aiOutput = analysis.raw_ai_output || {};
  const summary = aiOutput.summary || 'No summary available.';
  const skills = aiOutput.extracted_skills || [];
  const experience = aiOutput.experience_years ?? 0;
  const recommendations = aiOutput.recommendations || 'No recommendations available.';

  return (
    <div className="max-w-4xl mx-auto px-4 space-y-6">
      {/* Back Header */}
      <div>
        <button
          onClick={onBack}
          className="text-slate-500 hover:text-slate-800 text-xs font-medium inline-flex items-center gap-1.5 transition-colors focus:outline-none"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Workspace</span>
        </button>
      </div>

      {/* Hero Overview Panel */}
      <div className="simple-panel p-6 flex flex-col md:flex-row md:items-center justify-between gap-6 bg-white">
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-slate-100 rounded-lg flex items-center justify-center text-slate-600">
              <Cpu className="w-4 h-4" />
            </div>
            <h2 className="text-lg font-bold text-slate-900">AI Assessment Result</h2>
          </div>
          <p className="text-slate-500 text-xs leading-relaxed max-w-lg">
            Evaluation details generated by the AI agent against general tech roles.
          </p>
          <div className="flex items-center gap-4 pt-1 flex-wrap">
            <div className="flex items-center gap-1.5 text-slate-600 text-xs">
              <Calendar className="w-3.5 h-3.5 text-slate-400" />
              <span>{experience} Years Experience</span>
            </div>
            <div className="flex items-center gap-1.5 text-slate-600 text-xs">
              <Award className="w-3.5 h-3.5 text-slate-400" />
              <span>{skills.length} Extracted Skills</span>
            </div>
          </div>
        </div>

        {/* Flat Score Badge */}
        <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 w-28 text-center shrink-0 self-center md:self-auto">
          <div className="text-3xl font-extrabold text-indigo-600">{score}%</div>
          <div className="text-[10px] text-slate-450 uppercase tracking-wider font-semibold mt-0.5">
            Match Score
          </div>
        </div>
      </div>

      {/* Grid Content */}
      <div className="grid md:grid-cols-3 gap-6">
        {/* Left Side: Summary and Recommendations */}
        <div className="md:col-span-2 space-y-6">
          {/* Executive Summary Card */}
          <div className="simple-panel p-6 bg-white space-y-3">
            <h3 className="text-sm font-bold text-slate-800 flex items-center gap-2 border-b border-slate-100 pb-2">
              <Brain className="w-4 h-4 text-slate-500" />
              <span>Profile Summary</span>
            </h3>
            <p className="text-slate-600 text-xs leading-relaxed whitespace-pre-line">
              {summary}
            </p>
          </div>

          {/* Recommendations Card */}
          <div className="simple-panel p-6 bg-white space-y-3">
            <h3 className="text-sm font-bold text-slate-800 flex items-center gap-2 border-b border-slate-100 pb-2">
              <Lightbulb className="w-4 h-4 text-slate-500" />
              <span>Recommendations</span>
            </h3>
            <p className="text-slate-600 text-xs leading-relaxed whitespace-pre-line">
              {recommendations}
            </p>
          </div>
        </div>

        {/* Right Side: Skill Badges */}
        <div className="space-y-6">
          <div className="simple-panel p-5 bg-white space-y-4">
            <h3 className="text-sm font-bold text-slate-800 flex items-center gap-2 border-b border-slate-100 pb-2">
              <Award className="w-4 h-4 text-slate-500" />
              <span>Skills Badges</span>
            </h3>
            {skills.length === 0 ? (
              <p className="text-slate-400 text-xs italic">No skills identified.</p>
            ) : (
              <div className="flex flex-wrap gap-1.5">
                {skills.map((skill, index) => (
                  <span
                    key={index}
                    className="bg-slate-100 text-slate-700 border border-slate-200 text-xs px-2.5 py-1 rounded transition-colors"
                  >
                    {skill}
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
